---
driver:
  name: vagrant
  customize:
    memory: 2000
  network:
    - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[dev-box-cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
